"""
AdvisoryEngine — Generates farmer-facing advisory from decision output.

DESIGN PRINCIPLES:
  - Advisory is generated AFTER the DecisionEngine has assessed risk
  - Advisory text is NOT generated by an LLM
  - Advisory is based on structured templates keyed by (risk, crop, disease)
  - Templates are intentionally generic in Phase 1 — no crop-specific advice
  - Do NOT recommend specific pesticides or chemicals at this stage
  - Specific templates will be added after: crop scope + disease scope + agronomist validation

CURRENT STATE (Phase 1):
  Generic templates based on risk level only.
  All templates explicitly state they are generic placeholders.

FUTURE STATE:
  Add crop+disease+stage specific validated templates.
  Template registry can be loaded from database or config file.
"""
from __future__ import annotations

import logging
from typing import Optional

from app.schemas import DecisionResult, PredictionResult, SeverityResult, AdvisoryResult

logger = logging.getLogger(__name__)


# ── Template Registry ─────────────────────────────────────────────────────────
# Templates are keyed by (risk_level).
# Future: key by (risk_level, crop_id, disease).
# Each entry: {advisory_text, recommended_action, monitoring_recommendation}

_GENERIC_TEMPLATES: dict[str, dict] = {
    "LOW": {
        "advisory_text": (
            "Crop appears healthy or shows minimal signs of stress. "
            "Continue regular monitoring and maintain good agricultural practices. "
            "[Generic advisory — crop-specific guidance will be added after model selection.]"
        ),
        "recommended_action": "No immediate intervention required.",
        "monitoring_recommendation": (
            "Continue standard field observation schedule. "
            "Check crop again in 14 days or sooner if visible symptoms appear."
        ),
        "next_observation_days": 14,
    },
    "MEDIUM": {
        "advisory_text": (
            "Signs of disease or stress detected at moderate severity. "
            "Increase monitoring frequency. Consult an agronomist to confirm diagnosis "
            "before applying any treatment. Avoid unnecessary chemical applications. "
            "[Generic advisory — validated crop-specific guidance will be added after model selection.]"
        ),
        "recommended_action": (
            "Increase field inspection frequency. "
            "Document symptom progression with photographs."
        ),
        "monitoring_recommendation": (
            "Re-observe in 5 days. If symptoms worsen, escalate to HIGH protocol. "
            "Consult a certified agronomist before applying any treatment."
        ),
        "next_observation_days": 5,
    },
    "HIGH": {
        "advisory_text": (
            "High severity disease symptoms detected. Immediate action is recommended. "
            "Consult a certified agronomist for diagnosis confirmation and treatment plan. "
            "Do NOT apply pesticides based solely on this automated detection. "
            "Isolate affected area if possible to prevent spread. "
            "[Generic advisory — validated crop-specific guidance will be added after model selection.]"
        ),
        "recommended_action": (
            "Consult a certified agronomist immediately. "
            "Isolate the affected field section. "
            "Document and photograph affected plants."
        ),
        "monitoring_recommendation": (
            "Re-observe in 2 days after agronomist consultation. "
            "Track disease progression at every observation."
        ),
        "next_observation_days": 2,
    },
}


class AdvisoryEngine:
    """
    Generates structured advisory output from decision + prediction data.
    """

    def generate(
        self,
        decision: DecisionResult,
        prediction: PredictionResult,
        severity: SeverityResult,
        crop_id: Optional[str] = None,
        crop_stage: Optional[str] = None,
    ) -> AdvisoryResult:
        """
        Generates an advisory for the farmer.

        Future: look up crop+disease specific templates from a database table.
        Currently uses generic risk-level templates only.
        """
        risk = decision.risk
        template = _GENERIC_TEMPLATES.get(risk, _GENERIC_TEMPLATES["LOW"])

        source = "mock" if prediction.is_mock else "rule_based_generic"

        logger.info(
            "[ADVISORY] Generated advisory: risk=%s crop=%s disease=%s source=%s",
            risk, crop_id, prediction.disease, source,
        )

        return AdvisoryResult(
            advisory_text=template["advisory_text"],
            recommended_action=template["recommended_action"],
            monitoring_recommendation=template["monitoring_recommendation"],
            next_observation_days=decision.monitoring_interval_days
            or template.get("next_observation_days"),
            advisory_source=source,
        )
