"""
AgriSense API Schemas — Pydantic v2 request/response models.

The prediction contract is defined here and is the boundary between:
  - AIInferenceService (produces PredictionResult)
  - The rest of the system (consumes PredictionResult)

The Flutter mobile app is the consumer of the /predict API response.
The response schema must remain stable across model upgrades.
"""
from __future__ import annotations

import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field, field_validator


# ── Affected Region (segmentation support) ────────────────────────────────────

class AffectedRegionSegmentation(BaseModel):
    """
    Optional segmentation metadata from the AI model.
    Not required by classification-only models.
    Supported by future segmentation models without breaking the contract.
    """
    type: str = "segmentation"
    mask_url: Optional[str] = None         # URL to mask image (if stored)
    affected_area_percent: Optional[float] = None  # 0–100

    model_config = {"extra": "allow"}  # allow model-specific extra fields


# ── Prediction Contract ────────────────────────────────────────────────────────
# This is THE central interface between AI and the rest of the system.
# All downstream engines (Severity, Decision, Advisory) consume this.

class PredictionResult(BaseModel):
    """
    Structured output of the AIInferenceService.

    Rules:
    - disease: model-returned disease key (e.g. 'powdery_mildew', 'healthy')
    - confidence: 0.0–1.0 — raw model confidence score; NOT severity
    - affected_region: null for classification models; populated for segmentation
    - model_version: must always be present; required for model versioning

    IMPORTANT: confidence != severity. They are computed by separate engines.
    """
    disease: str = Field(..., description="Disease key from model (e.g. 'powdery_mildew')")
    disease_label: Optional[str] = Field(None, description="Human-readable disease name")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence 0.0–1.0")
    affected_region: Optional[AffectedRegionSegmentation] = Field(
        None,
        description="Segmentation output if the model supports it; null for classification-only models"
    )
    model_version: str = Field(..., description="Model version identifier e.g. 'v1', 'v2-grape'")

    # Indicates if this is a mock result (for development transparency)
    is_mock: bool = Field(False, description="True when generated by mock inference (USE_MOCK_INFERENCE=true)")


# ── Severity ──────────────────────────────────────────────────────────────────

class SeverityResult(BaseModel):
    """
    Output of the SeverityEngine.
    Computed independently from prediction confidence.
    """
    severity: float = Field(..., ge=0.0, le=100.0, description="Severity score 0–100")
    calculation_method: str = Field(..., description="Method used: 'mock', 'confidence_proxy', 'segmentation_area', etc.")


# ── Decision Engine ───────────────────────────────────────────────────────────

class DecisionResult(BaseModel):
    """
    Output of the DecisionEngine.
    Deterministic and explainable.
    """
    risk: str = Field(..., description="Risk level: LOW | MEDIUM | HIGH")
    decision_reason: str = Field(..., description="Explanation of why this risk level was assigned")
    # Advisory inputs — passed to AdvisoryEngine
    recommended_action_key: Optional[str] = Field(None, description="Action key for advisory lookup")
    monitoring_interval_days: Optional[int] = Field(None, description="Recommended monitoring interval")


# ── Advisory Engine ───────────────────────────────────────────────────────────

class AdvisoryResult(BaseModel):
    """
    Output of the AdvisoryEngine.
    Advisory is generated after DecisionEngine has produced a risk level.
    """
    advisory_text: str = Field(..., description="Primary advisory text for farmer")
    recommended_action: Optional[str] = Field(None, description="Immediate action recommendation")
    monitoring_recommendation: Optional[str] = Field(None, description="Ongoing monitoring advice")
    next_observation_days: Optional[int] = Field(None, description="Days until next observation recommended")
    advisory_source: str = Field("mock", description="Source: 'mock', 'rule_based', 'expert_system'")


# ── /predict API Request ───────────────────────────────────────────────────────

class PredictRequest(BaseModel):
    """
    Context sent with the image for prediction.
    These fields are available to the inference service and all downstream engines.
    """
    farm_id: int
    field_id: int
    crop_id: str = Field(..., description="Crop identifier e.g. 'wheat'")
    crop_stage: Optional[str] = Field(None, description="Crop growth stage e.g. 'flowering'")


# ── /predict API Response ──────────────────────────────────────────────────────

class PredictResponse(BaseModel):
    """
    Full response from the /predict endpoint.
    This is what the Flutter app receives.
    Stable across model versions — model_version field handles versioning.
    """
    # Raw prediction (from AI model)
    disease: str
    disease_label: Optional[str] = None
    confidence: float
    affected_region: Optional[AffectedRegionSegmentation] = None
    model_version: str

    # Severity (from SeverityEngine)
    severity: float

    # Decision (from DecisionEngine)
    risk: str
    decision_reason: Optional[str] = None

    # Trend (from TrendEngine — based on observation history)
    trend: Optional[str] = None  # IMPROVING | STABLE | INCREASING

    # Advisory (from AdvisoryEngine)
    advisory: str

    # Transparency
    is_mock: bool = False

    @classmethod
    def assemble(
        cls,
        prediction: PredictionResult,
        severity: SeverityResult,
        decision: DecisionResult,
        advisory: AdvisoryResult,
        trend: Optional[str] = None,
    ) -> "PredictResponse":
        """Assembles a full response from all engine outputs."""
        return cls(
            disease=prediction.disease,
            disease_label=prediction.disease_label,
            confidence=prediction.confidence,
            affected_region=prediction.affected_region,
            model_version=prediction.model_version,
            severity=severity.severity,
            risk=decision.risk,
            decision_reason=decision.decision_reason,
            trend=trend,
            advisory=advisory.advisory_text,
            is_mock=prediction.is_mock,
        )


# ── Auth Schemas ──────────────────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    full_name: str
    email: str
    password: str
    mobile_number: Optional[str] = None
    preferred_language: str = "en"


class LoginRequest(BaseModel):
    email: str
    password: str


class UserResponse(BaseModel):
    id: int
    full_name: str
    email: str
    mobile_number: Optional[str] = None
    preferred_language: str
    created_at: Optional[datetime.datetime] = None

    model_config = {"from_attributes": True}


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


# ── Farm Schemas ──────────────────────────────────────────────────────────────

class FarmCreate(BaseModel):
    name: str
    location: str = ""
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class FarmResponse(BaseModel):
    id: int
    name: str
    location: str
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    field_count: int = 0
    main_crop: Optional[str] = None
    current_health_status: Optional[str] = None
    owner_id: int

    model_config = {"from_attributes": True}


# ── Field Schemas ──────────────────────────────────────────────────────────────

class FieldCreate(BaseModel):
    farm_id: int
    name: str
    crop_id: str
    crop_variety: Optional[str] = None
    crop_stage: Optional[str] = None


class FieldResponse(BaseModel):
    id: int
    name: str
    farm_id: int
    crop_id: str
    crop_name: Optional[str] = None
    crop_variety: Optional[str] = None
    crop_stage: Optional[str] = None
    current_risk: Optional[str] = None
    latest_severity: Optional[float] = None

    model_config = {"from_attributes": True}


# ── Crop Schemas ──────────────────────────────────────────────────────────────

class CropResponse(BaseModel):
    id: str
    name: str
    scientific_name: Optional[str] = None
    description: Optional[str] = None

    model_config = {"from_attributes": True}


# ── Observation Schemas ───────────────────────────────────────────────────────

class ObservationCreate(BaseModel):
    farm_id: int
    field_id: int
    crop_id: str
    crop_stage: Optional[str] = None
    disease: Optional[str] = None
    disease_label: Optional[str] = None
    confidence: Optional[float] = None
    severity: Optional[float] = None
    risk: Optional[str] = None
    advisory: Optional[str] = None
    model_version: Optional[str] = None
    trend: Optional[str] = None


class ObservationResponse(BaseModel):
    id: int
    farm_id: int
    field_id: int
    crop_id: str
    crop_stage: Optional[str] = None
    image_url: Optional[str] = None
    observed_at: Optional[datetime.datetime] = None
    disease: Optional[str] = None
    disease_label: Optional[str] = None
    confidence: Optional[float] = None
    severity: Optional[float] = None
    risk: Optional[str] = None
    decision_reason: Optional[str] = None
    advisory: Optional[str] = None
    model_version: Optional[str] = None
    trend: Optional[str] = None

    model_config = {"from_attributes": True}


# ── Alert Schemas ─────────────────────────────────────────────────────────────

class AlertResponse(BaseModel):
    id: int
    observation_id: int
    field_id: int
    farm_id: int
    disease: str
    risk: str
    severity: float
    status: str
    created_at: datetime.datetime
    field_name: Optional[str] = None
    farm_name: Optional[str] = None

    model_config = {"from_attributes": True}


# ── Dashboard Schema ───────────────────────────────────────────────────────────

class DashboardSummary(BaseModel):
    farm_name: str
    location: str
    main_crop: Optional[str] = None
    field_name: Optional[str] = None
    latest_disease: Optional[str] = None
    confidence: Optional[float] = None
    severity: Optional[float] = None
    risk: Optional[str] = None
    trend: Optional[str] = None
    active_alert_count: int = 0
